(function(){var n,aa,ba=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");} 
var da=ca(this),ea=typeof Symbol==="function"&&typeof Symbol("x")==="symbol",p={},fa={};function q(a,b,c){if(!c||a!=null){c=fa[b];if(c==null)return a[b];c=a[c];return c!==void 0?c:a[b]}} 
function t(a,b,c){if(b)a:{var d=a.split(".");a=d.length===1;var e=d[0],f;!a&&e in p?f=p:f=da;for(e=0;e<d.length-1;e++){var g=d[e];if(!(g in f))break a;f=f[g]}d=d[d.length-1];c=ea&&c==="es6"?f[d]:null;b=b(c);b!=null&&(a?ba(p,d,{configurable:!0,writable:!0,value:b}):b!==c&&(fa[d]===void 0&&(a=Math.random()*1E9>>>0,fa[d]=ea?da.Symbol(d):"$jscp$"+a+"$"+d),ba(f,fa[d],{configurable:!0,writable:!0,value:b})))}}function ia(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}} 
function u(a){var b=typeof p.Symbol!="undefined"&&q(p.Symbol,"iterator")&&a[q(p.Symbol,"iterator")];if(b)return b.call(a);if(typeof a.length=="number")return{next:ia(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function ja(a){return ka(a,a)}function ka(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a}function w(a,b){return Object.prototype.hasOwnProperty.call(a,b)} 
var la=ea&&typeof q(Object,"assign")=="function"?q(Object,"assign"):function(a,b){if(a==null)throw new TypeError("No nullish arg");a=Object(a);for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)w(d,e)&&(a[e]=d[e])}return a};t("Object.assign",function(a){return a||la},"es6");function ma(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}t("globalThis",function(a){return a||da},"es_2020"); 
t("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.A=f;ba(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.A};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b},"es6"); 
t("Symbol.iterator",function(a){if(a)return a;a=(0,p.Symbol)("Symbol.iterator");ba(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return pa(ia(this))}});return a},"es6");function pa(a){a={next:a};a[q(p.Symbol,"iterator")]=function(){return this};return a} 
t("WeakMap",function(a){function b(g){this.A=(f+=Math.random()+1).toString();if(g){g=u(g);for(var h;!(h=g.next()).done;)h=h.value,this.set(h[0],h[1])}}function c(){}function d(g){var h=typeof g;return h==="object"&&g!==null||h==="function"}if(function(){if(!a||!Object.seal)return!1;try{var g=Object.seal({}),h=Object.seal({}),k=new a([[g,2],[h,3]]);if(k.get(g)!=2||k.get(h)!=3)return!1;k.delete(g);k.set(h,4);return!k.has(g)&&k.get(h)==4}catch(l){return!1}}())return a;var e="$jscomp_hidden_"+Math.random(), 
f=0;b.prototype.set=function(g,h){if(!d(g))throw Error("Invalid WeakMap key");if(!w(g,e)){var k=new c;ba(g,e,{value:k})}if(!w(g,e))throw Error("WeakMap key fail: "+g);g[e][this.A]=h;return this};b.prototype.get=function(g){return d(g)&&w(g,e)?g[e][this.A]:void 0};b.prototype.has=function(g){return d(g)&&w(g,e)&&w(g[e],this.A)};b.prototype.delete=function(g){return d(g)&&w(g,e)&&w(g[e],this.A)?delete g[e][this.A]:!1};return b},"es6"); 
t("Map",function(a){function b(){var h={};return h.H=h.next=h.head=h}function c(h,k){var l=h[1];return pa(function(){if(l){for(;l.head!=h[1];)l=l.H;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(h,k){var l=k&&typeof k;l=="object"||l=="function"?f.has(k)?l=f.get(k):(l=""+ ++g,f.set(k,l)):l="p_"+k;var m=h[0][l];if(m&&w(h[0],l))for(h=0;h<m.length;h++){var r=m[h];if(k!==k&&r.key!==r.key||k===r.key)return{id:l,list:m,index:h,entry:r}}return{id:l, 
list:m,index:-1,entry:void 0}}function e(h){this[0]={};this[1]=b();this.size=0;if(h){h=u(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!="function"||!q(a.prototype,"entries")||typeof Object.seal!="function")return!1;try{var h=Object.seal({x:4}),k=new a(u([[h,"s"]]));if(k.get(h)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var l=q(k,"entries").call(k),m=l.next();if(m.done||m.value[0]!=h||m.value[1]!="s")return!1;m=l.next();return m.done|| 
m.value[0].x!=4||m.value[1]!="t"||!l.next().done?!1:!0}catch(r){return!1}}())return a;var f=new p.WeakMap;e.prototype.set=function(h,k){h=h===0?0:h;var l=d(this,h);l.list||(l.list=this[0][l.id]=[]);l.entry?l.entry.value=k:(l.entry={next:this[1],H:this[1].H,head:this[1],key:h,value:k},l.list.push(l.entry),this[1].H.next=l.entry,this[1].H=l.entry,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.entry&&h.list?(h.list.splice(h.index,1),h.list.length||delete this[0][h.id], 
h.entry.H.next=h.entry.next,h.entry.next.H=h.entry.H,h.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].H=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).entry};e.prototype.get=function(h){return(h=d(this,h).entry)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,function(h){return h.value})}; 
e.prototype.forEach=function(h,k){for(var l=q(this,"entries").call(this),m;!(m=l.next()).done;)m=m.value,h.call(k,m[1],m[0],this)};e.prototype[q(p.Symbol,"iterator")]=q(e.prototype,"entries");var g=0;return e},"es6");function qa(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[q(p.Symbol,"iterator")]=function(){return e};return e} 
t("Array.prototype.entries",function(a){return a?a:function(){return qa(this,function(b,c){return[b,c]})}},"es6");t("Array.prototype.keys",function(a){return a?a:function(){return qa(this,function(b){return b})}},"es6");function ra(a,b,c){if(a==null)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""} 
t("String.prototype.endsWith",function(a){return a?a:function(b,c){var d=ra(this,b,"endsWith");c===void 0&&(c=d.length);c=Math.max(0,Math.min(c|0,d.length));for(var e=b.length;e>0&&c>0;)if(d[--c]!=b[--e])return!1;return e<=0}},"es6");t("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)w(b,d)&&c.push([d,b[d]]);return c}},"es8");t("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}},"es6"); 
t("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||q(Object,"is").call(Object,f,b))return!0}return!1}},"es7");t("String.prototype.includes",function(a){return a?a:function(b,c){return ra(this,b,"includes").indexOf(b,c||0)!==-1}},"es6");t("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)w(b,d)&&c.push(b[d]);return c}},"es8"); 
t("Array.prototype.values",function(a){return a?a:function(){return qa(this,function(b,c){return c})}},"es8");t("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}},"es6");/* 
 
 Copyright The Closure Library Authors. 
 SPDX-License-Identifier: Apache-2.0 
*/ 
var z=this||self;function B(a){a=parseFloat(a);return isNaN(a)||a>1||a<0?0:a};function sa(a){sa[" "](a);return a}sa[" "]=function(){};function ta(a){try{var b;if(b=!!a&&a.location.href!=null)a:{try{sa(a.foo);b=!0;break a}catch(c){}b=!1}return b}catch(c){return!1}};function ua(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};function va(){var a=z.navigator;return a&&(a=a.userAgent)?a:""};/* 
 
 Copyright Google LLC 
 SPDX-License-Identifier: Apache-2.0 
*/ 
var wa=p.globalThis.trustedTypes,xa;function ya(){var a=null;if(!wa)return a;try{var b=function(c){return c};a=wa.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(c){}return a}function Aa(){xa===void 0&&(xa=ya());return xa};function Ba(a){this.A=a}Ba.prototype.toString=function(){return this.A+""};function Ga(a){var b=Aa();a=b?b.createScriptURL(a):a;return new Ba(a)}function Ha(a){if(a instanceof Ba)return a.A;throw Error("");};var Ia=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;function Ja(a){this.A=a}Ja.prototype.toString=function(){return this.A+""};function Ka(a){var b=Aa();a=b?b.createHTML(a):a;return new Ja(a)}function La(a){if(a instanceof Ja)return a.A;throw Error("");};function Ma(a,b){a.src=Ha(b);var c;b=a.ownerDocument;b=b===void 0?document:b;var d;b=(d=(c=b).querySelector)==null?void 0:d.call(c,"script[nonce]");(c=b==null?"":b.nonce||b.getAttribute("nonce")||"")&&a.setAttribute("nonce",c)};var Na=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};function Oa(a,b){a.write(La(b))};var Pa=ua(function(){return va().indexOf("MSIE")!=-1});function Qa(a){return va().indexOf(a)!=-1}var Ra=ua(function(){var a=Math.random;return["Google Web Preview","Mediapartners-Google","Google-Read-Aloud","Google-Adwords"].some(Qa)||a()<1E-4});function Sa(a,b){if(a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(a[c],c,a)};function Ta(){if(!p.globalThis.crypto)return Math.random();try{var a=new Uint32Array(1);p.globalThis.crypto.getRandomValues(a);return a[0]/65536/65536}catch(b){return Math.random()}};function Ua(a){return a instanceof Ja?a:Ka(String(a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;"))}function Va(a){return Wa(a)}function Wa(a){var b=Ua("");return Ka(a.map(function(c){return La(Ua(c))}).join(La(b).toString()))} 
var Xa=/^[a-z][a-z\d-]*$/i,ab="APPLET BASE EMBED IFRAME LINK MATH META OBJECT SCRIPT STYLE SVG TEMPLATE".split(" "),bb="AREA BR COL COMMAND HR IMG INPUT KEYGEN PARAM SOURCE TRACK WBR".split(" "),cb=["action","formaction","href"]; 
function db(a){var b;if(!Xa.test("span"))throw Error("");if(ab.indexOf("SPAN")!==-1)throw Error("");var c="<span";a&&(c+=eb(a));Array.isArray(b)||(b=b===void 0?[]:[b]);bb.indexOf("SPAN")!==-1?c+=">":(a=Va(b.map(function(d){return d instanceof Ja?d:Ua(String(d))})),c+=">"+a.toString()+"</span>");return Ka(c)} 
function eb(a){for(var b="",c=q(Object,"keys").call(Object,a),d=0;d<c.length;d++){var e=c[d],f=a[e];if(!Xa.test(e))throw Error("");if(f!==void 0&&f!==null){if(/^on./i.test(e))throw Error("");cb.indexOf(e.toLowerCase())!==-1&&(f=String(f),f=Ia.test(f)?f:void 0,f=f||"about:invalid#zClosurez");e=e+'="'+Ua(String(f))+'"';b+=" "+e}}return b};function fb(a){var b=ma.apply(1,arguments);if(b.length===0)return Ga(a[0]);for(var c=a[0],d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return Ga(c)}function gb(a,b,c,d){function e(g,h){g!=null&&(Array.isArray(g)?g.forEach(function(k){return e(k,h)}):(b+=f+encodeURIComponent(h)+"="+encodeURIComponent(g),f="&"))}var f=b.length?"&":"?";d.constructor===Object&&(d=q(Object,"entries").call(Object,d));Array.isArray(d)?d.forEach(function(g){return e(g[1],g[0])}):d.forEach(e);return Ga(a+b+c)};function C(a){return/^true$/.test(a)}function hb(a,b){if(!a||!b.head)return null;var c=ib("META");b.head.appendChild(c);c.httpEquiv="origin-trial";c.content=a;return c}function ib(a,b){b=b===void 0?document:b;return b.createElement(String(a).toLowerCase())};var jb=B("0.20"),kb=B("0.002"),lb=B("1.0"),mb=B("1.0"),nb=B("1.0"),ob=B("0.00"),pb=B("0.00"),qb=C("false"),rb=C("true"),sb=C("true"),tb=C("true"),ub=C("true"),vb=C("true");var wb=null;function xb(a){a=a===void 0?window:a;if(wb===null){wb="";try{var b="";try{b=a.top.location.hash}catch(d){b=a.location.hash}if(b){var c=b.match(/\bdeid=([\d,]+)/);wb=c?c[1]:""}}catch(d){}}return wb} 
function E(a,b,c){var d=F;if(c?d.A.hasOwnProperty(c)&&d.A[c]==="":1){var e=e===void 0?z:e;e=(e=xb(e))?(e=e.match(new RegExp("\\b("+a.join("|")+")\\b")))?e[0]:null:null;if(e)a=e;else a:{if(!Pa()&&!Ra()&&(e=Math.random(),e<b)){e=Ta();a=a[Math.floor(e*a.length)];break a}a=null}a&&a!==""&&(c?d.A.hasOwnProperty(c)&&(d.A[c]=a):d.ca[a]=!0)}}function G(a){var b=F;return b.A.hasOwnProperty(a)?b.A[a]:""} 
function yb(){var a=F,b=[];Sa(a.ca,function(c,d){b.push(d)});Sa(a.A,function(c){c!==""&&b.push(c)});return b};var zb={Ta:2,ab:13,Za:14,Wa:16,Va:17,Ua:18,Sa:19,cb:20,bb:21,Ra:22,Na:23},F=null;function Ab(){return!!F&&(G(20)=="466465926"||G(20)=="466465925")}function Bb(){return!!F&&G(16)=="592230571"}function Cb(){return!!F&&(G(22)=="512247839"||G(22)=="512247838")};function Db(a){var b=b===void 0?z:b;var c,d;return((c=b.performance)==null?void 0:(d=c.timing)==null?void 0:d[a])||0};function Eb(){var a=Gb,b="U";if(a.U&&a.hasOwnProperty(b))return a.U;b=new a;return a.U=b};var Hb={Xa:0,Oa:1,Ya:2,Qa:3,Pa:4};function Gb(){this.A={}}function Ib(a,b,c){typeof c==="number"&&c>0&&(a.A[b]=Math.round(c))}function Jb(a){var b=Eb();var c=c===void 0?z:c;c=c.performance;Ib(b,a,c&&c.now?c.now():null)}function Kb(){function a(){return Ib(b,0,Db("loadEventStart")-Db("navigationStart"))}var b=Eb();Db("loadEventStart")!=0?a():window.addEventListener("load",a)}function Lb(){var a=Eb();return q(Object,"values").call(Object,Hb).map(function(b){return[b,a.A[b]||0]})};var ac=C("false");function bc(a){return typeof a==="function"}function cc(a){return typeof a==="string"}function dc(a,b){if(a&&Array.isArray(a))for(var c=0;c<a.length;c++)if(a[c]&&b(a[c]))return a[c]}function ec(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(c,a[c])}function fc(){return(new Date(Date.now())).getTime()}function hc(a,b){return a.length>=b.length&&a.substring(a.length-b.length,a.length)===b} 
function ic(a){for(var b=0;b<3;++b)try{var c=decodeURIComponent(a).replace(/\+/g," ");if(c===a)break;a=c}catch(d){return""}return a};var jc={};function H(a){var b=jc.TAGGING;b||(b=jc.TAGGING=[]);b[a]=!0};function kc(a){a=lc(a);return Ka(a)}function lc(a){return a===null?"null":a===void 0?"undefined":a};var I=window,J=document,mc=navigator,nc={async:1,nonce:1,onerror:1,onload:1,src:1,type:1},oc={height:1,onload:1,src:1,style:1,width:1};function pc(a,b,c){b&&ec(b,function(d,e){d=d.toLowerCase();c.hasOwnProperty(d)||a.setAttribute(d,e)})} 
function qc(a,b,c,d,e){var f=J.createElement("script");pc(f,d,nc);f.type="text/javascript";f.async=d&&d.async===!1?!1:!0;a=Ga(lc(a));Ma(f,a);b&&(f.onload=b);c&&(f.onerror=c);e?e.appendChild(f):(b=J.getElementsByTagName("script")[0]||J.body||J.head,b.parentNode.insertBefore(f,b))} 
function rc(a,b,c){var d=!1;d=d===void 0?!0:d;var e=!1;c||(c=J.createElement("iframe"),e=!0);pc(c,void 0,oc);d&&(c.height="0",c.width="0",c.style.display="none",c.style.visibility="hidden");a!==void 0&&(c.src=a);e&&(a=J.body&&J.body.lastChild||J.body||J.head,a.parentNode.insertBefore(c,a));b&&(c.onload=b)}var sc={cache:"no-store",credentials:"include",keepalive:!0,method:"POST",mode:"no-cors",redirect:"follow"}; 
function tc(a){if(bc(I.fetch)){var b=q(Object,"assign").call(Object,{},sc);try{var c=I.fetch(a,b);if(c)return c.then(function(){}).catch(function(){}),!0}catch(d){}}uc(a);return!0}function vc(){var a=I.performance;if(a&&a.getEntriesByType)try{var b=a.getEntriesByType("navigation");if(b&&b.length>0)var c=b[0].type}catch(d){return"e"}if(!c)return"u";switch(c){case "navigate":return"n";case "back_forward":return"h";case "reload":return"r";case "prerender":return"p";default:return"x"}} 
function wc(a){var b=new Image(1,1);pc(b,void 0,{});b.onload=function(){b.onload=null};b.onerror=function(){b.onerror=null};b.src=a}function uc(a){try{var b=mc.sendBeacon&&mc.sendBeacon(a)}catch(c){H(15)}b||wc(a)};function xc(){var a={};var b=I.google_tag_data;I.google_tag_data=b===void 0?a:b;a=I.google_tag_data;return a.ics=a.ics||new yc}function yc(){this.entries={};this.waitPeriodTimedOut=this.wasSetLate=this.accessedAny=this.accessedDefault=this.usedImplicit=this.usedUpdate=this.usedDefault=this.usedDeclare=this.active=!1;this.A=[]}n=yc.prototype; 
n.default=function(a,b,c,d,e,f,g){this.usedDefault||this.usedDeclare||!this.accessedDefault&&!this.accessedAny||(this.wasSetLate=!0);this.usedDefault=this.active=!0;H(19);b==null?H(18):zc(this,a,b==="granted",c,d,e,f,g)};n.waitForUpdate=function(a,b,c){for(var d=0;d<a.length;d++)zc(this,a[d],void 0,void 0,"","",b,c)}; 
function zc(a,b,c,d,e,f,g,h){var k=q(a,"entries"),l=k[b]||{},m=l.region;d=d&&cc(d)?d.toUpperCase():void 0;e=e.toUpperCase();f=f.toUpperCase();if(e===""||d===f||(d===e?m!==f:!d&&!m)){f=!!(g&&g>0&&l.update===void 0);var r={region:d,declare_region:l.declare_region,implicit:l.implicit,default:c!==void 0?c:l.default,declare:l.declare,update:l.update,quiet:f};if(e!==""||l.default!==!1)k[b]=r;f&&I.setTimeout(function(){k[b]===r&&r.quiet&&(H(2),a.waitPeriodTimedOut=!0,a.clearTimeout(b,void 0,h),a.notifyListeners())}, 
g)}}n.clearTimeout=function(a,b,c){var d=[a],e=c.delegatedConsentTypes,f;for(f in e)e.hasOwnProperty(f)&&e[f]===a&&d.push(f);e=q(this,"entries")[a]||{};a=this.getConsentState(a,c);if(e.quiet)for(e.quiet=!1,b=u(d),d=b.next();!d.done;d=b.next())Ac(this,d.value);else if(b!==void 0&&a!==b)for(b=u(d),d=b.next();!d.done;d=b.next())Ac(this,d.value)}; 
n.update=function(a,b,c){this.usedDefault||this.usedDeclare||this.usedUpdate||!this.accessedAny||(this.wasSetLate=!0);this.usedUpdate=this.active=!0;if(b!=null){var d=this.getConsentState(a,c),e=q(this,"entries");(e[a]=e[a]||{}).update=b==="granted";this.clearTimeout(a,d,c)}}; 
n.declare=function(a,b,c,d,e){this.usedDeclare=this.active=!0;var f=q(this,"entries"),g=f[a]||{},h=g.declare_region;c=c&&cc(c)?c.toUpperCase():void 0;d=d.toUpperCase();e=e.toUpperCase();if(d===""||c===e||(c===d?h!==e:!c&&!h))if(b={region:g.region,declare_region:c,declare:b==="granted",implicit:g.implicit,default:g.default,update:g.update,quiet:g.quiet},d!==""||g.declare!==!1)f[a]=b}; 
n.implicit=function(a,b){this.usedImplicit=!0;var c=q(this,"entries");a=c[a]=c[a]||{};a.implicit!==!1&&(a.implicit=b==="granted")}; 
n.getConsentState=function(a,b){var c=q(this,"entries"),d=c[a]||{},e=d.update;if(e!==void 0)return e?1:2;if(b.usedContainerScopedDefaults){e=b.containerScopedDefaults[a];if(e===3)return 1;if(e===2)return 2}else if(e=d.default,e!==void 0)return e?1:2;if(b==null?0:b.delegatedConsentTypes.hasOwnProperty(a)){a=b.delegatedConsentTypes[a];c=c[a]||{};e=c.update;if(e!==void 0)return e?1:2;if(b.usedContainerScopedDefaults){b=b.containerScopedDefaults[a];if(b===3)return 1;if(b===2)return 2}else if(e=c.default, 
e!==void 0)return e?1:2}e=d.declare;if(e!==void 0)return e?1:2;e=d.implicit;return e!==void 0?e?3:4:0};n.addListener=function(a,b){this.A.push({consentTypes:a,Ia:b})};function Ac(a,b){for(var c=0;c<a.A.length;++c){var d=a.A[c];Array.isArray(d.consentTypes)&&d.consentTypes.indexOf(b)!==-1&&(d.ga=!0)}}n.notifyListeners=function(a,b){for(var c=0;c<this.A.length;++c){var d=this.A[c];if(d.ga){d.ga=!1;try{d.Ia({consentEventId:a,consentPriorityId:b})}catch(e){}}}};var Bc=[];function L(a){return Bc[a]===void 0?!1:Bc[a]};var Cc={},Dc={delegatedConsentTypes:{},corePlatformServices:{},usedCorePlatformServices:!1,selectedAllCorePlatformServices:!1,containerScopedDefaults:(Cc.ad_storage=1,Cc.analytics_storage=1,Cc.ad_user_data=1,Cc.ad_personalization=1,Cc),usedContainerScopedDefaults:!1};function M(a){var b=xc();b.accessedAny=!0;return(cc(a)?[a]:a).every(function(c){switch(b.getConsentState(c,Dc)){case 1:case 3:return!0;case 2:case 4:return!1;default:return!0}})} 
function Ec(a){var b=xc();b.accessedAny=!0;return!(q(b,"entries")[a]||{}).quiet}function Fc(a,b){xc().addListener(a,b)}function Gc(a,b){if(b.every(Ec))a({});else{var c=!1;Fc(b,function(d){!c&&b.every(Ec)&&(c=!0,a(d))})}} 
function Hc(a,b){function c(){return d.filter(function(g){return M(g)&&!e[g]})}var d=cc(b)?[b]:b,e={};b=c();if(b.length!==d.length){var f=function(g){g=u(g);for(var h=g.next();!h.done;h=g.next())e[h.value]=!0};f(b);Fc(d,function(g){function h(m){m.length!==0&&(f(m),g.consentTypes=m,a(g))}var k=c();if(k.length!==0){var l=q(Object,"keys").call(Object,e).length;k.length+l>=d.length?h(k):I.setTimeout(function(){h(c())},500)}})}};var Ic=/:[0-9]+$/,Jc=/^\d+\.fls\.doubleclick\.net$/;function Kc(a,b){var c={};a=u(a.split("&"));for(var d=a.next();!d.done;d=a.next()){var e=u(d.value.split("="));d=e.next().value;for(var f,g=[];!(f=e.next()).done;)g.push(f.value);e=g;d=decodeURIComponent(d.replace(/\+/g," "));if(b===void 0||d===b)e=e.join("="),c[d]||(c[d]=[]),c[d].push(decodeURIComponent(e.replace(/\+/g," ")))}var h;return(h=c[b])==null?void 0:h[0]} 
function N(a,b,c,d,e){b&&(b=String(b).toLowerCase());if(b==="protocol"||b==="port")a.protocol=Lc(a.protocol)||Lc(I.location.protocol);b==="port"?a.port=String(Number(a.hostname?a.port:I.location.port)||(a.protocol==="http"?80:a.protocol==="https"?443:"")):b==="host"&&(a.hostname=(a.hostname||I.location.hostname).replace(Ic,"").toLowerCase());var f=Lc(a.protocol);b&&(b=String(b).toLowerCase());switch(b){case "url_no_fragment":d="";a&&a.href&&(d=a.href.indexOf("#"),d=d<0?a.href:a.href.substring(0,d)); 
a=d;break;case "protocol":a=f;break;case "host":a=a.hostname.replace(Ic,"").toLowerCase();c&&(d=/^www\d*\./.exec(a))&&d[0]&&(a=a.substring(d[0].length));break;case "port":a=String(Number(a.port)||(f==="http"?80:f==="https"?443:""));break;case "path":a.pathname||a.hostname||H(1);a=a.pathname.charAt(0)==="/"?a.pathname:"/"+a.pathname;a=a.split("/");(d||[]).indexOf(a[a.length-1])>=0&&(a[a.length-1]="");a=a.join("/");break;case "query":a=a.search.replace("?","");e&&(a=Kc(a,e));break;case "extension":a= 
a.pathname.split(".");a=a.length>1?a[a.length-1]:"";a=a.split("/")[0];break;case "fragment":a=a.hash.replace("#","");break;default:a=a&&a.href}return a}function Lc(a){return a?a.replace(":","").toLowerCase():""}var Mc={},Nc=0; 
function Oc(a){var b=Mc[a];if(!b){b=J.createElement("a");a&&(b.href=a);var c=b.pathname;c[0]!=="/"&&(a||H(1),c="/"+c);var d=b.hostname.replace(Ic,"");b={href:b.href,protocol:b.protocol,host:b.host,hostname:d,pathname:c,search:b.search,hash:b.hash,port:b.port};Nc<5&&(Mc[a]=b,Nc++)}return b};function Pc(a,b,c,d){var e,f=Number(a.X!=null?a.X:void 0);f!==0&&(e=new Date((b||fc())+1E3*(f||7776E3)));return{path:a.path,domain:a.domain,flags:a.flags,encode:!!c,expires:e,K:d}};var Qc=["ad_storage","ad_user_data"];function Rc(a,b){if(a)if(b===null||b===void 0||b==="")H(33);else{var c=Sc(!1);c.error!==0?H(34):c.value?(c.value[a]=b,Tc(c)!==0&&H(36)):H(35)}else H(32)}function Uc(a){if(!a)return H(27),{error:10};var b=Sc();if(b.error!==0)return H(29),b;if(!b.value)return H(30),{error:2};if(!(a in b.value))return H(31),{value:void 0,error:15};a=b.value[a];return a===null||a===void 0||a===""?(H(28),{value:void 0,error:11}):{value:a,error:0}} 
function Vc(a){if(a){var b=Sc(!1);b.error!==0?H(38):b.value?a in b.value?(delete b.value[a],Tc(b)!==0&&H(41)):H(40):H(39)}else H(37)} 
function Sc(a){a=a===void 0?!0:a;if(!M(Qc))return H(43),{error:3};try{if(!I.localStorage)return H(44),{error:1}}catch(f){return H(45),{error:14}}var b={schema:"gcl",version:1},c=void 0;try{c=I.localStorage.getItem("_gcl_ls")}catch(f){return H(46),{error:13}}try{if(c){var d=JSON.parse(c);if(d&&typeof d==="object")b=d;else return H(47),{error:12}}}catch(f){return H(48),{error:8}}if(b.schema!=="gcl")return H(49),{error:4};if(b.version!==1)return H(50),{error:5};try{var e=Wc(b);a&&e&&Tc({value:b,error:0})}catch(f){return H(48), 
{error:8}}return{value:b,error:0}}function Wc(a){if(!a||typeof a!=="object")return!1;if("expires"in a&&"value"in a){var b;typeof a.expires==="number"?b=a.expires:b=typeof a.expires==="string"?Number(a.expires):NaN;if(isNaN(b)||!(Date.now()<=b))return a.value=null,a.error=9,H(54),!0}else{b=!1;for(var c=u(q(Object,"keys").call(Object,a)),d=c.next();!d.done;d=c.next())b=Wc(a[d.value])||b;return b}return!1} 
function Tc(a){if(a.error)return a.error;if(!a.value)return H(42),2;a=a.value;try{var b=JSON.stringify(a)}catch(c){return H(52),6}try{I.localStorage.setItem("_gcl_ls",b)}catch(c){return H(53),7}return 0};var Xc={M:"value",G:"conversionCount",Y:1},Yc=[Xc,{P:6,R:7,M:"timeouts",G:"timeouts",Y:0},{P:8,R:9,M:"errors",G:"errors",Y:0},{P:10,R:11,M:"eopCount",G:"endOfPageCount",Y:0}];function Zc(a){return M(["ad_storage","ad_user_data"])?!a.R||L(a.R):!1}function $c(a){return M(["ad_storage","ad_user_data"])?!a.P||L(a.P):!1};function ad(){return M(["ad_storage","ad_user_data"])&&L(21)};var O={v:{za:0,ia:1,ma:2,na:3,oa:4,ka:5,la:6,pa:7,qa:8,ta:9,ra:10,sa:11,ua:12,va:13,wa:14,ya:15,xa:16,Aa:17,Ba:18,Ca:19,Da:20,Ea:21,Fa:22,S:23,ea:24}};O.v[O.v.za]="RESERVED_ZERO";O.v[O.v.ia]="ADS_CONVERSION_HIT";O.v[O.v.ma]="CONTAINER_EXECUTE_START";O.v[O.v.na]="CONTAINER_SETUP_END";O.v[O.v.oa]="CONTAINER_SETUP_START";O.v[O.v.ka]="CONTAINER_BLOCKING_END";O.v[O.v.la]="CONTAINER_EXECUTE_END";O.v[O.v.pa]="CONTAINER_YIELD_END";O.v[O.v.qa]="CONTAINER_YIELD_START";O.v[O.v.ta]="EVENT_EXECUTE_END"; 
O.v[O.v.ra]="EVENT_EVALUATION_END";O.v[O.v.sa]="EVENT_EVALUATION_START";O.v[O.v.ua]="EVENT_SETUP_END";O.v[O.v.va]="EVENT_SETUP_START";O.v[O.v.wa]="GA4_CONVERSION_HIT";O.v[O.v.ya]="PAGE_LOAD";O.v[O.v.xa]="PAGEVIEW";O.v[O.v.Aa]="SNIPPET_LOAD";O.v[O.v.Ba]="TAG_CALLBACK_ERROR";O.v[O.v.Ca]="TAG_CALLBACK_FAILURE";O.v[O.v.Da]="TAG_CALLBACK_SUCCESS";O.v[O.v.Ea]="TAG_EXECUTE_END";O.v[O.v.Fa]="TAG_EXECUTE_START";O.v[O.v.S]="CUSTOM_PERFORMANCE_START";O.v[O.v.ea]="CUSTOM_PERFORMANCE_END";var bd=[],cd={};function dd(a){if(L(18)&&q(bd,"includes").call(bd,a)){var b;(b=I.performance||void 0)==null||b.mark(a+"-"+O.v.S+"-"+(cd[a]||0))}}function ed(a){if(L(18)&&q(bd,"includes").call(bd,a)){var b=a+"-"+O.v.ea+"-"+(cd[a]||0),c={start:a+"-"+O.v.S+"-"+(cd[a]||0),end:b},d;(d=I.performance||void 0)==null||d.mark(b);var e,f;((f=(e=I.performance||void 0)==null?void 0:e.measure(b,c))==null?void 0:f.duration)!==void 0&&(cd[a]=(cd[a]||0)+1)}};function fd(a,b,c,d){try{dd("3");var e;return(e=gd(function(f){return f===a},b,c,d)[a])!=null?e:[]}finally{ed("3")}}function gd(a,b,c,d){if(hd(d)){d={};b=String(b||id()).split(";");for(var e=0;e<b.length;e++){var f=b[e].split("="),g=f[0].trim();if(g&&a(g)){(f=f.slice(1).join("=").trim())&&c&&(f=decodeURIComponent(f));var h=void 0,k=void 0;((h=d)[k=g]||(h[k]=[])).push(f)}}a=d}else a={};return a} 
function jd(a,b,c){var d=kd,e=["ad_storage","ad_user_data"];if(hd(e)){a=ld(a,d,e);if(a.length===1)return a[0];if(a.length!==0){a=md(a,function(f){return f.Ha},b);if(a.length===1)return a[0];a=md(a,function(f){return f.Ma},c);return a[0]}}}function nd(a,b,c,d){var e=id(),f=window;f.origin!=="null"&&(f.document.cookie=a);a=id();return e!==a||c!==void 0&&fd(b,a,!1,d).indexOf(c)>=0} 
function od(a,b,c){function d(r,v,x){if(x==null)return delete g[v],r;g[v]=x;return r+"; "+v+"="+x}function e(r,v){if(v==null)return r;g[v]=!0;return r+"; "+v}if(hd(c.K)){if(b==null)var f=a+"=deleted; expires="+(new Date(0)).toUTCString();else c.encode&&(b=encodeURIComponent(b)),b=pd(b),f=a+"="+b;var g={};f=d(f,"path",c.path);if(c.expires instanceof Date)var h=c.expires.toUTCString();else c.expires!=null&&(h=c.expires);f=d(f,"expires",h);f=d(f,"max-age",c.fb);f=d(f,"samesite",c.hb);c.secure&&(f=e(f, 
"secure"));if((h=c.domain)&&h.toLowerCase()==="auto"){h=qd();for(var k=0;k<h.length;++k){var l=h[k]!=="none"?h[k]:void 0,m=d(f,"domain",l);m=e(m,c.flags);if(!rd(l,c.path)&&nd(m,a,b,c.K))break}}else h&&h.toLowerCase()!=="none"&&(f=d(f,"domain",h)),f=e(f,c.flags),rd(h,c.path)||nd(f,a,b,c.K)}}function sd(a,b,c){c.path==null&&(c.path="/");c.domain||(c.domain="auto");dd("2");od(a,b,c);ed("2")} 
function md(a,b,c){for(var d=[],e=[],f,g=0;g<a.length;g++){var h=a[g],k=b(h);k===c?d.push(h):f===void 0||k<f?(e=[h],f=k):k===f&&e.push(h)}return d.length>0?d:e}function ld(a,b,c){var d=[];a=fd(a,void 0,void 0,c);for(c=0;c<a.length;c++){var e=a[c].split("."),f=e.shift();if(!b||!f||b.indexOf(f)!==-1)if(f=e.shift())f=f.split("-"),d.push({eb:a[c],Ga:e.join("."),Ha:Number(f[0])||1,Ma:Number(f[1])||1})}return d}function pd(a){a&&a.length>1200&&(a=a.substring(0,1200));return a} 
var td=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,ud=/(^|\.)doubleclick\.net$/i;function rd(a,b){return a!==void 0&&(ud.test(window.document.location.hostname)||b==="/"&&td.test(a))}function vd(a){if(!a)return 1;var b=a;L(4)&&a==="none"&&(b=window.document.location.hostname);b=b.indexOf(".")===0?b.substring(1):b;return b.split(".").length}function wd(a){if(!a||a==="/")return 1;a[0]!=="/"&&(a="/"+a);a[a.length-1]!=="/"&&(a+="/");return a.split("/").length-1} 
function xd(a,b){a=""+vd(a);b=wd(b);b>1&&(a+="-"+b);return a}function id(){return window.origin!=="null"?window.document.cookie:""}function hd(a){return a&&L(5)?(Array.isArray(a)?a:[a]).every(function(b){return Ec(b)&&M(b)}):!0} 
function qd(){var a=[],b=window.document.location.hostname.split(".");if(b.length===4){var c=b[b.length-1];if(Number(c).toString()===c)return["none"]}for(c=b.length-2;c>=0;c--)a.push(b.slice(c).join("."));b=window.document.location.hostname;ud.test(b)||td.test(b)||a.push("none");return a};var kd=["1"],yd={},zd={}; 
function Ad(a,b){(b===void 0?0:b)&&Zc(Xc)&&Vc("gcl_ctr");if(b=$c(Xc)){var c=[Xc];b:{b=Uc("gcl_ctr");if(b.error===0&&b.value&&typeof b.value==="object"){b=b.value;try{var d="value"in b&&typeof b.value==="object"?b.value:void 0;break b}catch(h){}}d=void 0}b={};c=u(c);for(var e=c.next();!e.done;e=c.next())if(e=e.value,d&&Zc(e)){var f=d[e.M];f===void 0||q(Number,"isNaN").call(Number,f)?b[e.G]=-1:b[e.G]=Number(f)}else b[e.G]=-1;b=b[Xc.G]===-1}if(b){d={};d=(d[Xc.G]=0,d);b=u(Yc);for(c=b.next();!c.done;c= 
b.next())c=c.value,c!==Xc&&$c(c)&&(d[c.G]=0);b=fc();a=Pc(a||{},b,!0);c={};e=u(Yc);for(f=e.next();!f.done;f=e.next()){f=f.value;var g=d[f.G];g!==void 0&&g!==-1&&(c[f.M]=g)}c.creationTimeMs=b;Rc("gcl_ctr",{value:c,expires:Number(a.expires)})}} 
function Bd(a,b){(b===void 0?0:b)&&ad()&&Vc("last_convs");if(!(b=!(M(["ad_storage","ad_user_data"])&&L(22))))a:{if(ad()&&(b=Uc("last_convs"),b.error===0&&b.value&&typeof b.value==="object"&&(b=b.value,b.value&&Array.isArray(b.value)))){var c=b.value;if(!(c.length>1)){b=[];c=u(c);for(var d=c.next();!d.done;d=c.next()){d=d.value;if(typeof d!=="object"||d===null||typeof d.random!=="number"||typeof d.label!=="string"||d.label.length>200){b=void 0;break a}b.push({random:d.random,label:d.label})}break a}}b= 
void 0}b||(b=[],!ad()||b.length>1||b.length===1&&b[0].label.length>200||(a=a||{},Rc("last_convs",{value:b,expires:Number(Pc(a).expires)})))}function ce(a,b,c,d){b=["1",xd(c.domain,c.path),b].join(".");c=Pc(c,d);c.K=["ad_storage","ad_user_data"];sd(a,b,c)} 
function he(a,b,c){var d;b=(d=jd(a,vd(b),wd(c)))==null?void 0:d.Ga;if(!b)return!1;d=b.split(".");d.length===5?(yd[a]=d.slice(0,2).join("."),zd[a]={id:d.slice(2,4).join("."),V:Number(d[4])||0}):d.length===3?zd[a]={id:d.slice(0,2).join("."),V:Number(d[2])||0}:yd[a]=b;return!0}function ie(a){return(a||"_gcl")+"_au"};function je(a,b,c){a=ke(a,!0);if(a[b])return!1;a[b]=[];a[b][0]=c;return!0}function ke(a,b){var c=a.GooglebQhCsO;c||(c={},b&&(a.GooglebQhCsO=c));return c};var le={},me=null; 
function ne(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);e>255&&(b[c++]=e&255,e>>=8);b[c++]=e}a=4;a===void 0&&(a=0);if(!me)for(me={},c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;e<5;e++){var f=c.concat(d[e].split(""));le[e]=f;for(var g=0;g<f.length;g++){var h=f[g];me[h]===void 0&&(me[h]=g)}}a=le[a];c=Array(Math.floor(b.length/3));d=a[64]||"";for(e=f=0;f<b.length-2;f+=3){var k=b[f],l=b[f+1];h=b[f+2];g=a[k>>2];k=a[(k& 
3)<<4|l>>4];l=a[(l&15)<<2|h>>6];h=a[h&63];c[e++]=g+k+l+h}g=0;h=d;switch(b.length-f){case 2:g=b[f+1],h=a[(g&15)<<2]||d;case 1:b=b[f],c[e]=a[b>>2]+a[(b&3)<<4|g>>4]+h+d}return c.join("")};var oe=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function pe(a){var b=a.match(oe);a=b[5];var c=b[6];b=b[7];var d="";a&&(d+=a);c&&(d+="?"+c);b&&(d+="#"+b);return d}function qe(a,b,c,d){for(var e=c.length;(b=a.indexOf(c,b))>=0&&b<d;){var f=a.charCodeAt(b-1);if(f==38||f==63)if(f=a.charCodeAt(b+e),!f||f==61||f==38||f==35)return b;b+=e+1}return-1}var re=/#|$/; 
function se(a,b){var c=a.search(re),d=qe(a,0,b,c);if(d<0)return null;var e=a.indexOf("&",d);if(e<0||e>c)e=c;d+=b.length+1;return decodeURIComponent(a.slice(d,e!==-1?e:0).replace(/\+/g," "))}var te=/[?&]($|#)/; 
function ue(a,b,c){for(var d=a.search(re),e=0,f,g=[];(f=qe(a,e,b,d))>=0;)g.push(a.substring(e,f)),e=Math.min(a.indexOf("&",f)+1||d,d);g.push(a.slice(e));a=g.join("").replace(te,"$1");c=c!=null?"="+encodeURIComponent(String(c)):"";(b+=c)?(c=a.indexOf("#"),c<0&&(c=a.length),d=a.indexOf("?"),d<0||d>c?(d=c,e=""):e=a.substring(d+1,c),c=[a.slice(0,d),e,a.slice(c)],a=c[1],c[1]=b?a?a+"&"+b:b:a,b=c[0]+(c[1]?"?"+c[1]:"")+c[2]):b=a;return b};function ve(a,b,c,d,e,f){var g=se(c,"fmt");if(d){var h=se(c,"random"),k=se(c,"label")||"";if(!h)return;h=ne(decodeURIComponent(k.replace(/\+/g," "))+":"+decodeURIComponent(h.replace(/\+/g," ")));if(!je(a,h,d))return}g&&Number(g)!==4?(c=ue(c,"rfmt",g),c=ue(c,"fmt",4)):g||(c=ue(c,"fmt",4));qc(c,function(){a.google_noFurtherRedirects&&d&&(a.google_noFurtherRedirects=null,d())},function(){e==null||e()},f,b.getElementsByTagName("script")[0].parentElement||void 0);return c};var P={},we=(P.k={F:/^[\w-]+$/},P.b={F:/^[\w-]+$/,Z:!0},P.i={F:/^[1-9]\d*$/},P.h={F:/^\d+$/},P.t={F:/^[1-9]\d*$/},P.d={F:/^[A-Za-z0-9_-]+$/},P.j={F:/^\d+$/},P.u={F:/^[1-9]\d*$/},P.l={F:/^[01]$/},P.o={F:/^[1-9]\d*$/},P.g={F:/^[01]$/},P.s={F:/^.+$/},P.m={F:/^[01]$/},P);var xe={},Be=(xe[5]={ba:{2:ye},W:"2",N:["k","i","b","u"]},xe[4]={ba:{2:ye,GCL:ze},W:"2",N:["k","i","b","m"]},xe[2]={ba:{GS2:ye,GS1:Ae},W:"GS2",N:"sogtjlhd".split("")},xe); 
function ye(a,b){a=a.split(".");if(a.length===3){var c=a[2];if(c.indexOf("$")===-1&&c.indexOf("%24")!==-1)try{c=decodeURIComponent(c)}catch(h){}a={};if(b=Be[b]){b=b.N;c=u(c.split("$"));for(var d=c.next();!d.done;d=c.next()){d=d.value;var e=d[0];if(b.indexOf(e)!==-1)try{var f=decodeURIComponent(d.substring(1)),g=we[e];g&&(g.Z?(a[e]=a[e]||[],a[e].push(f)):a[e]=f)}catch(h){}}return a}}}function ze(a){a=a.split(".");a.shift();var b=a.shift(),c=a.shift(),d={};return d.k=c,d.i=b,d.b=a,d} 
function Ae(a){a=a.split(".").slice(2);if(!(a.length<5||a.length>7)){var b={};return b.s=a[0],b.o=a[1],b.g=a[2],b.t=a[3],b.j=a[4],b.l=a[5],b.h=a[6],b}};var Ce=new p.Map([[5,"ad_storage"],[4,["ad_storage","ad_user_data"]],[2,"analytics_storage"]]);function De(a,b){if(Be[b]){var c=[];a=fd(a,void 0,void 0,Ce.get(b));a=u(a);for(var d=a.next();!d.done;d=a.next()){a:{d=d.value;var e=b,f=Be[e];if(f){var g=d.split(".")[0];if(g&&(f=f.ba[g])){d=f(d,e);break a}}d=void 0}d&&c.push(Ee(d))}return c}} 
function Fe(a,b,c,d){c=c||{};var e=Be[5];if(e){e=e.W;var f=xd(c.domain,c.path)||"1";var g=Be[5];if(g){var h=[];g=u(g.N);for(var k=g.next();!k.done;k=g.next()){k=k.value;var l=we[k];if(l){var m=b[k];if(m!==void 0)if(l.Z&&Array.isArray(m))for(l=u(m),m=l.next();!m.done;m=l.next())h.push(encodeURIComponent(k+m.value));else h.push(encodeURIComponent(k+m))}}b=h.join("$")}else b=void 0;b=[e,f,b].join(".")}else b=void 0;b&&(c=Pc(c,d,void 0,Ce.get(5)),sd(a,b,c))} 
function Ge(a,b){b=b.F;return typeof b==="function"?b(a):b.test(a)}function Ee(a){for(var b=u(q(Object,"keys").call(Object,a)),c=b.next(),d={};!c.done;d={L:void 0},c=b.next()){c=c.value;var e=a[c];d.L=we[c];d.L?d.L.Z?a[c]=Array.isArray(e)?e.filter(function(f){return function(g){return Ge(g,f.L)}}(d)):void 0:typeof e==="string"&&Ge(e,d.L)||(a[c]=void 0):a[c]=void 0}return a};function S(){this.value=this.value=0}S.prototype.set=function(a){return this.value|=1<<a};function He(a,b){b<=0||(a.value|=1<<b-1)}S.prototype.get=function(){return this.value};function Ie(a){var b=[],c=J.cookie.split(";");a=new RegExp("^\\s*"+(a||"_gac")+"_(UA-\\d+-\\d+)=\\s*(.+?)\\s*$");for(var d=0;d<c.length;d++){var e=c[d].match(a);e&&b.push({aa:e[1],value:e[2],timestamp:Number(e[2].split(".")[1])||0})}b.sort(function(f,g){return g.timestamp-f.timestamp});return b} 
function Je(a,b){a=Ie(a);var c={};if(!a||!a.length)return c;for(var d=0;d<a.length;d++){var e=a[d].value.split(".");if(!(e[0]!=="1"||b&&e.length<3||!b&&e.length!==3)&&Number(e[1])){c[a[d].aa]||(c[a[d].aa]=[]);var f={version:e[0],timestamp:Number(e[1])*1E3,B:e[2]};b&&e.length>3&&(f.labels=e.slice(3));c[a[d].aa].push(f)}}return c};var Ke=/^\w+$/,T=/^[\w-]+$/,Le={},Me=(Le.aw="FPGCLAW",Le),U={},Ne=(U.ag="_ag",U.gb="_gb",U.aw="_aw",U.dc="_dc",U.gf="_gf",U.ha="_ha",U.gp="_gp",U.gs="_gs",U);function X(){return["ad_storage","ad_user_data"]}function Y(a){return!L(5)||M(a)}function Oe(a){function b(){var d=Y(c);d&&a();return d}var c=X();Gc(function(){b()||Hc(b,c)},c)}function Pe(a){return Qe(a).map(function(b){return b.B})} 
function Re(a,b){function c(e){return function(f){f.fa=e;return f}}b=b===void 0?!1:b;var d=Se(a.prefix);a=Te("gb",d);d=Te("ag",d);if(!d||!a)return[];b=Qe(a,b).map(c("gb"));a=Ue(d).map(c("ag"));return b.concat(a).sort(function(e,f){return f.timestamp-e.timestamp})}function Ve(a,b,c,d,e){var f=dc(a,function(g){return g.B===b});f?(f.timestamp<c&&(f.timestamp=c,f.J=e),f.labels=We(f.labels||[],d||[])):a.push({version:"2",B:b,timestamp:c,labels:d,J:e})} 
function Xe(a){var b=De(a,5)||[];a=[];b=u(b);for(var c=b.next();!c.done;c=b.next()){var d=c=c.value,e=c?(Number(c.i)||0)*1E3:0;e&&Ve(a,d.k,e,d.b||[],c.u)}return a.sort(function(f,g){return g.timestamp-f.timestamp})}function Qe(a,b){b=b===void 0?!1:b;var c=[];Ye(c,a,1);if(b)if(hc(a,"_aw")){if(a=Ze())a.J=void 0,a.C=a.C||[2],$e(c,a);L(12)&&Ye(c,"gcl_aw",2)}else hc(a,"_gb")&&L(13)&&Ye(c,"gcl_gb",2);c.sort(function(d,e){return e.timestamp-d.timestamp});return af(c)} 
function bf(a,b){var c=[];a=u(a);for(var d=a.next();!d.done;d=a.next())d=d.value,q(c,"includes").call(c,d)||c.push(d);b=u(b);for(a=b.next();!a.done;a=b.next())a=a.value,q(c,"includes").call(c,a)||c.push(a);return c} 
function $e(a,b,c){c=c===void 0?!1:c;for(var d,e,f=u(a),g=f.next();!g.done;g=f.next()){g=g.value;if(g.B===b.B){d=g;break}g.D&&b.D&&g.D.value===b.D.value&&(e=g)}if(d){var h,k;a=(h=d.D)!=null?h:new S;h=(k=b.D)!=null?k:new S;a.value|=h.value;d.D=a;d.timestamp<b.timestamp&&(d.timestamp=b.timestamp,d.J=b.J);d.labels=bf(d.labels||[],b.labels||[]);d.C=bf(d.C||[],b.C||[])}else c&&e?q(Object,"assign").call(Object,e,b):a.push(b)} 
function Ze(){var a=Uc("gclid");if(!a||a.error||!a.value||typeof a.value!=="object")return null;a=a.value;try{if(!("value"in a&&a.value)||typeof a.value!=="object")return null;var b=a.value,c=b.value;if(!c||!c.match(T))return null;var d=b.linkDecorationSource,e=b.linkDecorationSources,f=new S;if(typeof d==="number")if(d){var g=new S;d===1?(He(g,2),He(g,3)):He(g,d);f=g}else f=new S;else typeof e==="number"&&(f.value=e);return{version:"",B:c,timestamp:Number(b.creationTimeMs)||0,labels:[],D:f,C:[2]}}catch(h){return null}} 
function cf(a){a=Uc(a);if(a.error!==0)return null;try{return a.value.reduce(function(b,c){if(!c.value||typeof c.value!=="object")return b;var d=c.value,e=d.value;if(!e||!e.match(T))return b;var f=new S,g=d.linkDecorationSources;typeof g==="number"&&(f.value=g);var h;b.push({version:"",B:e,timestamp:Number(d.creationTimeMs)||0,expires:Number(c.expires)||0,labels:(h=d.labels)!=null?h:[],D:f,C:[2]});return b},[])}catch(b){return null}} 
function Ye(a,b,c){if(c===1){b=fd(b,J.cookie,void 0,X());b=u(b);for(var d=b.next();!d.done;d=b.next())d=df(d.value.split(".")),d=d.length===0?null:{version:d[0],B:d[2],timestamp:(Number(d[1])||0)*1E3,labels:d.slice(3)},d!=null&&(d.J=void 0,d.D=new S,d.C=[c],$e(a,d))}else if(c===2&&(c=cf(b)))for(c=u(c),b=c.next();!b.done;b=c.next())b=b.value,b.J=void 0,b.C=b.C,$e(a,b)}function Ue(a){return Xe(a).map(function(b){b.D=new S;b.C=[1];return b})} 
function We(a,b){if(!a.length)return b;if(!b.length)return a;var c={};return a.concat(b).filter(function(d){return c.hasOwnProperty(d)?!1:c[d]=!0})}function Se(a){return a&&typeof a==="string"&&a.match(Ke)?a:"_gcl"} 
function ef(a,b){var c=Oc(a);a=N(c,"query",!1,void 0,"gclid");var d=N(c,"query",!1,void 0,"gclsrc"),e=N(c,"query",!1,void 0,"wbraid");if(e){var f=e;try{f=decodeURIComponent(e)}catch(k){}f=f.split(",");e=f.length===2&&f[0]===f[1]?f[0]:e}f=N(c,"query",!1,void 0,"gbraid");var g=N(c,"query",!1,void 0,"gad_source"),h=N(c,"query",!1,void 0,"dclid");!b||a&&d&&e&&f||(b=c.hash.replace("#",""),a=a||Kc(b,"gclid"),d=d||Kc(b,"gclsrc"),e=e||Kc(b,"wbraid"),f=f||Kc(b,"gbraid"),g=g||Kc(b,"gad_source"));return ff(a, 
d,h,e,f,g)} 
function ff(a,b,c,d,e,f){function g(k,l){h[l]||(h[l]=[]);h[l].push(k)}var h={};h.gclid=a;h.gclsrc=b;h.dclid=c;if(a!==void 0&&a.match(T))switch(b){case void 0:g(a,"aw");break;case "aw.ds":g(a,"aw");g(a,"dc");break;case "aw.dv":L(17)&&(g(a,"aw"),g(a,"dc"));break;case "ds":g(a,"dc");break;case "3p.ds":g(a,"dc");break;case "gf":g(a,"gf");break;case "ha":g(a,"ha")}c&&g(c,"dc");d!==void 0&&T.test(d)&&(h.wbraid=d,g(d,"gb"));e!==void 0&&T.test(e)&&(h.gbraid=e,g(e,"ag"));f!==void 0&&T.test(f)&&(h.gad_source= 
f,g(f,"gs"));return h} 
function gf(a,b){function c(){if(Y(f)&&a.length>0&&e.expires!==void 0){var g=cf("gcl_gb")||[];a.forEach(function(h){$e(g,{version:"",B:h.B,timestamp:d,expires:Number(e.expires),D:h.D,labels:h.labels},!0)});Rc("gcl_gb",g.map(function(h){var k={value:h.B,creationTimeMs:h.timestamp,linkDecorationSources:h.D?h.D.get():0},l;if((l=h.labels)==null?0:l.length)k.labels=h.labels;return{value:k,expires:Number(h.expires)}}))}}b=b||{};var d=fc(),e=Pc(b,d,!0),f=X();Gc(function(){Y(f)?c():Hc(c,f)},f)} 
function hf(a,b,c,d,e){function f(){if(Y(l)){var x=Pc(c,h,!0);x.K=l;for(var D=function(A,Fb){var za=Te(A,g);za&&(sd(za,Fb,x),A!=="gb"&&(m=!0))},K=function(A){A=["GCL",k,A];e.length>0&&A.push(e.join("."));return A.join(".")},Q=u(["aw","dc","gf","ha","gp"]),R=Q.next();!R.done;R=Q.next())R=R.value,a[R]&&D(R,K(a[R][0]));if((!m||v)&&a.gb){var ha=a.gb[0];Q=Te("gb",g);!b&&Qe(Q).some(function(A){return A.B===ha&&A.labels&&A.labels.length>0})||D("gb",K(ha))}}if(!r&&a.gbraid&&Y("ad_storage")&&(r=!0,!m||v)){var Ya= 
a.gbraid;D=Te("ag",g);if(b||!Ue(D).some(function(A){return A.B===Ya&&A.labels&&A.labels.length>0}))K={},K=(K.k=Ya,K.i=""+k,K.b=e,K),Fe(D,K,c,h)}jf(a,g,h,c)}c=c||{};e=e||[];var g=Se(c.prefix),h=d||fc(),k=Math.round(h/1E3),l=X(),m=!1,r=!1,v=L(19);Gc(function(){f();Y(l)||Hc(f,l)},l)} 
function jf(a,b,c,d){if(a.gad_source!==void 0&&Y("ad_storage")){var e=vc();if(e!=="r"&&e!=="h"&&(b=Te("gs",b))){e=(e=I.performance)&&bc(e.now)?e.now():void 0;e=Math.floor((fc()-(e||0))/1E3);var f=I.location.hostname;var g=I.location.pathname;f=ic(f);f.split(".").length>2&&(f=f.replace(/^(www[0-9]*|web|ftp|wap|home|m|w|amp|mobile)\./,""));g=ic(g);g=g.split(";")[0];g=g.replace(/\/(ar|slp|web|index)?\/?$/,"");g=(f+g).toLowerCase();f=1;var h;if(g)for(f=0,h=g.length-1;h>=0;h--){var k=g.charCodeAt(h);f= 
(f<<6&268435455)+k+(k<<14);k=f&266338304;f=k!==0?f^k>>21:f}g=String(f);f={};a=(f.k=a.gad_source,f.i=""+e,f.u=g,f);Fe(b,a,d,c)}}}function Te(a,b){a=Ne[a];if(a!==void 0)return b+a}function kf(a){return df(a.split(".")).length!==0?(Number(a.split(".")[1])||0)*1E3:0}function df(a){return a.length<3||a[0]!=="GCL"&&a[0]!=="1"||!/^\d+$/.test(a[1])||!T.test(a[2])?[]:a}function af(a){return a.filter(function(b){return T.test(b.B)})} 
function lf(){var a=["aw"],b={};if(I.origin!=="null"){for(var c=Se(b.prefix),d={},e=0;e<a.length;e++)Ne[a[e]]&&(d[a[e]]=Ne[a[e]]);Oe(function(){ec(d,function(f,g){g=fd(c+g,J.cookie,void 0,X());g.sort(function(m,r){return kf(r)-kf(m)});if(g.length){var h=g[0];g=kf(h);var k=df(h.split(".")).length!==0?h.split(".").slice(3):[],l={};h=df(h.split(".")).length!==0?h.split(".")[2]:void 0;l[f]=[h];hf(l,!0,b,g,k)}})})}} 
function mf(a,b,c,d,e){e=e===void 0?!1:e;var f=[];c=c||{};if(!Y(X()))return f;var g=Qe(a,e);var h=[];if(g.length!==0)for(var k={},l=0;l<g.length;l++){var m=g[l],r=m.fa?m.fa:"gcl";if((m.labels||[]).indexOf(b)===-1){f.push(0);var v=!1,x=void 0;if((x=m.C)==null?0:q(x,"includes").call(x,2))v=!0;x=void 0;((x=m.C)==null?0:q(x,"includes").call(x,1))&&!k[r]&&(v=!0,k[r]=!0);v&&h.push(m)}else if(f.push(1),v=void 0,(v=m.C)==null?0:q(v,"includes").call(v,1))k[r]=!0}if(h.length&&!d){d=[];g=!1;h=u(h);for(k=h.next();!k.done;k= 
h.next()){m=k=k.value;v=m.version;x=m.B;r=m.timestamp;l=m.C;m=(m.labels||[]).concat([b]);var D=void 0;((D=l)==null?0:q(D,"includes").call(D,1))&&!g&&(g=[v,Math.round(r/1E3),x].concat(m).join("."),r=Pc(c,r,!0),r.K=X(),sd(a,g,r),g=!0);r=void 0;e&&((r=l)==null?0:q(r,"includes").call(r,2))&&d.push(q(Object,"assign").call(Object,{},k,{labels:m}))}d.length&&gf(d,c)}return f} 
function nf(a,b){b=Se(b);b=Te(a,b);if(!b)return 0;a=a==="ag"?Ue(b):Qe(b);for(var c=b=0;c<a.length;c++)b=Math.max(b,a[c].timestamp);return b}function of(a){for(var b=0,c=u(q(Object,"keys").call(Object,a)),d=c.next();!d.done;d=c.next()){d=a[d.value];for(var e=0;e<d.length;e++)b=Math.max(b,Number(d[e].timestamp))}return b};var pf=RegExp("^UA-\\d+-\\d+%3A[\\w-]+(?:%2C[\\w-]+)*(?:%3BUA-\\d+-\\d+%3A[\\w-]+(?:%2C[\\w-]+)*)*$"),qf=/^~?[\w-]+(?:\.~?[\w-]+)*$/,rf=/^\d+\.fls\.doubleclick\.net$/,sf=/;gac=([^;?]+)/,tf=/;gacgb=([^;?]+)/; 
function uf(a,b,c){if(rf.test(a.location.host)){if((b=a.location.href.match(c))&&b.length===2&&b[1].match(pf)){a:{try{var d=decodeURIComponent(b[1]);break a}catch(h){}d=void 0}b=d||""}else b="";return b}d=[];a=u(q(Object,"keys").call(Object,b));for(c=a.next();!c.done;c=a.next()){c=c.value;for(var e=[],f=b[c],g=0;g<f.length;g++)e.push(f[g].B);d.push(c+":"+e.join(","))}return d.length>0?d.join(";"):""} 
function vf(a,b,c,d){for(var e=Y(X())?Je("_gac_gb",!0):{},f=[],g=!1,h=u(q(Object,"keys").call(Object,e)),k=h.next();!k.done;k=h.next()){k=k.value;var l=mf("_gac_gb_"+k,b,c,d);g=g||l.length!==0&&l.some(function(m){return m===1});f.push(k+":"+l.join(","))}return{Ka:g?f.join(";"):"",Ja:uf(a,e,tf)}}function wf(a,b){return(a=a.location.href.match(new RegExp(";"+b+"=([^;?]+)")))&&a.length===2&&a[1].match(qf)?a[1]:void 0} 
function xf(a,b,c,d){var e=e===void 0?!1:e;if(rf.test(a.location.host)){if(a=wf(a,d)){if(e){var f=new S;He(f,2);He(f,3);return a.split(".").map(function(h){return{B:h,D:f,C:[1]}})}return a.split(".").map(function(h){return{B:h,D:new S,C:[1]}})}}else{if(c==="gclid"){var g=Qe((b||"_gcl")+"_aw",e);L(24)&&yf().forEach(function(h){$e(g,h)});return g}if(c==="wbraid")return Qe((b||"_gcl")+"_gb",e);if(c==="braids")return Re({prefix:b},e)}return[]} 
function yf(){return(De(Me.aw,4)||[]).filter(function(a){return a.m==="1"}).map(function(a){return{B:a.k,timestamp:Number(a.i),version:"",C:[5]}})}function zf(a,b){return xf(a,b,"gclid","gclaw").map(function(c){return c.B}).join(".")}function Af(a,b){return xf(a,b,"wbraid","gclgb").map(function(c){return c.B}).join(".")} 
function Bf(a){if(Pe("_gcl_aw").length===0&&(!a||Pe(a+"_aw").length===0)){a=ef(I.location.href,!0);for(var b=!0,c=u(q(Object,"keys").call(Object,a)),d=c.next();!d.done;d=c.next())if(a[d.value]!==void 0){b=!1;break}b&&(a=ef(I.document.referrer,!1),a.gad_source=void 0);hf(a,!1,{});lf()}}function Cf(a,b,c){a=mf((b&&b.prefix||"_gcl")+"_gb",a,b,c,!1);return a.length===0||a.every(function(d){return d===0})?"":a.join(".")};function Df(){var a=I.__uspapi;if(bc(a)){var b="";try{a("getUSPData",1,function(c,d){d&&c&&(c=c.uspString)&&RegExp("^[\\da-zA-Z-]{1,20}$").test(c)&&(b=c)})}catch(c){}return b}};function Ef(){var a=a===void 0?document:a;var b;return!((b=a.featurePolicy)==null||!(aa=b.allowedFeatures(),q(aa,"includes")).call(aa,"attribution-reporting"))};var Ff="platform platformVersion architecture model uaFullVersion bitness fullVersionList wow64".split(" ");function Gf(a){var b;return(b=a.google_tag_data)!=null?b:a.google_tag_data={}}function Hf(a){a=a.google_tag_data;if(a!=null&&a.uach){a=a.uach;var b=q(Object,"assign").call(Object,{},a);a.fullVersionList&&(b.fullVersionList=a.fullVersionList.slice(0));a=b}else a=null;return a} 
function If(a){var b,c;return typeof((b=a.navigator)==null?void 0:(c=b.userAgentData)==null?void 0:c.getHighEntropyValues)==="function"}function Jf(){var a=window;if(If(a)){var b=Gf(a);b.uach_promise||(a=a.navigator.userAgentData.getHighEntropyValues(Ff).then(function(c){b.uach!=null||(b.uach=c);return c}),b.uach_promise=a)}};var Kf=/^[a-zA-Z0-9_]+$/,Lf=!1,Mf="google_conversion_id google_conversion_format google_conversion_type google_conversion_order_id google_conversion_language google_conversion_value google_conversion_currency google_conversion_domain google_conversion_label google_conversion_color google_disable_viewthrough google_enable_display_cookie_match google_gtag_event_data google_remarketing_only google_conversion_linker google_tag_for_child_directed_treatment google_tag_for_under_age_of_consent google_allow_ad_personalization_signals google_restricted_data_processing google_conversion_items google_conversion_merchant_id google_user_id google_custom_params google_conversion_date google_conversion_time google_conversion_js_version onload_callback opt_image_generator google_gtm_url_processor google_conversion_page_url google_conversion_referrer_url google_gcl_cookie_prefix google_gcl_cookie_path google_gcl_cookie_flags google_gcl_cookie_domain google_gcl_cookie_max_age_seconds google_read_gcl_cookie_opt_out google_basket_feed_country google_basket_feed_language google_basket_discount google_basket_transaction_type google_additional_conversion_params google_additional_params google_transport_url google_gtm_experiments".split(" "), 
Nf=["google_conversion_first_time","google_conversion_snippets"];function Of(a){return a!=null?encodeURIComponent(String(a)):""}function Pf(a){if(a!=null){a=String(a).substring(0,512);var b=a.indexOf("#");return b==-1?a:a.substring(0,b)}return""}function Z(a,b){b=Of(b);return b!=""&&(a=Of(a),a!="")?"&".concat(a,"=",b):""}function Qf(a){var b=typeof a;return a==null||b=="object"||b=="function"?null:String(a).replace(/,/g,"\\,").replace(/;/g,"\\;").replace(/=/g,"\\=")} 
function Rf(a){if(!a||typeof a!="object"||typeof a.join=="function")return"";var b=[],c;for(c in a)if(Object.prototype.hasOwnProperty.call(a,c)){var d=a[c];if(d&&typeof d.join==="function"){for(var e=[],f=0;f<d.length;++f){var g=Qf(d[f]);g!=null&&e.push(g)}d=e.length==0?null:e.join(",")}else d=Qf(d);(e=Qf(c))&&d!=null&&b.push(e+"="+d)}return b.join(";")}function Sf(a){return typeof a!="number"&&typeof a!="string"?"":Of(a.toString())} 
function Tf(a,b){if(b.google_read_gcl_cookie_opt_out||b.google_remarketing_only||b.google_conversion_domain&&(!b.google_gcl_cookie_prefix||!/^_ycl/.test(b.google_gcl_cookie_prefix)))return"";var c="",d=Uf(b),e={};b.google_gcl_cookie_domain&&(e.domain=b.google_gcl_cookie_domain);b.google_gcl_cookie_flags&&(e.flags=b.google_gcl_cookie_flags);b.google_gcl_cookie_max_age_seconds!=null&&(e.X=b.google_gcl_cookie_max_age_seconds);b.google_gcl_cookie_path&&(e.path=b.google_gcl_cookie_path);d&&(e.prefix=d); 
if(Vf(b)&&b.T)var f=b.O===void 0;else rf.test(a.location.host)?f=!(wf(a,"gclaw")||wf(a,"gac")):(f=Math.max(nf("aw",d),of(Y(X())?Je():{})),f=Math.max(nf("gb",d),of(Y(X())?Je("_gac_gb",!0):{}))>f);if(f){if(b.O!==void 0)return b.O;c=Af(a,d||void 0);f=b.google_conversion_label;var g=Cf(f,e,b.T);c=Z("gclgb",c)+(g?Z("mcov",g):"");if(d)return b.O=c;d=vf(a,f,e,b.T);a=d.Ja;d=d.Ka;c+=(a?Z("gacgb",a):"")+(d?Z("gacmcov",d):"");return b.O=c}if(d)return b=zf(a,d),Z("gclaw",b);(b=zf(a))&&(c=Z("gclaw",b));b=uf(a, 
Y(X())?Je():{},sf);return c+(b?Z("gac",b):"")}function Wf(a){function b(d){try{return decodeURIComponent(d),!0}catch(e){return!1}}a=a?a.title:"";if(a==void 0||a=="")return"";a=encodeURIComponent(a);for(var c=256;!b(a.substr(0,c));)c--;return"&tiba="+a.substr(0,c)} 
function Xf(a,b,c,d){var e="https://",f=c.google_conversion_type==="landing"?"/extclk":"/";switch(d){default:return"";case 2:case 3:var g="googleads.g.doubleclick.net/";var h="pagead/viewthroughconversion/";break;case 1:g="www.google.com/";h="pagead/1p-conversion/";break;case 6:g="www.google.com/";h="ccm/conversion/";break;case 0:g=c.google_conversion_domain||"www.googleadservices.com/";h="pagead/conversion/";break;case 5:g=c.google_conversion_domain||"www.googleadservices.com/";h="ccm/conversion/"; 
break;case 4:var k=c.google_gtm_experiments;g=k&&k.apcm?"www.google.com":k&&k.capiorig?c.google_conversion_id+".privacysandbox.googleadservices.com":"www.google.com/";h="pagead/privacysandbox/conversion/"}qb&&c.google_transport_url&&(g=c.google_transport_url);g[g.length-1]!=="/"&&(g+="/");if(g.indexOf("http://")===0||g.indexOf("https://")===0)e="";var l=[e,g,h,Of(c.google_conversion_id),f,"?random=",Of(c.google_conversion_time)].join(""),m=l,r=Z("cv",c.google_conversion_js_version),v=Z("fst",c.google_conversion_first_time), 
x=Z("num",c.google_conversion_snippets),D=Z("fmt",c.google_conversion_format),K=c.google_remarketing_only?Z("userId",c.google_user_id):"",Q=c.google_tag_for_child_directed_treatment;var R=Q==null||Q!==0&&Q!==1?"":Z("tfcd",Q);var ha=c.google_tag_for_under_age_of_consent;var Ya=ha==null||ha!==0&&ha!==1?"":Z("tfua",ha);var A=c.google_allow_ad_personalization_signals;var Fb=A===!1?Z("npa",1):A===!0?Z("npa",0):"";var za=c.google_restricted_data_processing;var kg=sb?za===!0?Z("rdp",1):za===!1?Z("rdp",0): 
"":"";var lg=Z("value",c.google_conversion_value),mg=Z("currency_code",c.google_conversion_currency),ng=Z("label",c.google_conversion_label),og=Z("oid",c.google_conversion_order_id),pg=Z("bg",c.google_conversion_color);a:{var Cd=c.google_conversion_language;if(Cd!=null){var Ca=Cd.toString();if(2==Ca.length){var Mb=Z("hl",Ca);break a}if(5==Ca.length){Mb=Z("hl",Ca.substring(0,2))+Z("gl",Ca.substring(3,5));break a}}Mb=""}var qg=Z("guid","ON"),rg=!c.google_conversion_domain&&"GooglemKTybQhCsO"in z&&typeof z.GooglemKTybQhCsO== 
"function"?Z("resp","GooglemKTybQhCsO"):"",sg=Z("disvt",c.google_disable_viewthrough),tg=Z("eid",yb().join()),Nb=[];if(a){var Ob=a.screen;Ob&&(Nb.push(Z("u_h",Ob.height)),Nb.push(Z("u_w",Ob.width)))}var ug=Nb.join("");var wg=Yf(),xg=Z("ig",/googleadservices\.com/.test("www.googleadservices.com")?1:0),Dd=Rf(c.google_custom_params),Ed=Rf(),Fd=Dd.concat(Dd.length>0&&Ed.length>0?";":"",Ed);var yg=Fd==""?"":"&".concat("data=",encodeURIComponent(Fd));var zg=Tf(b,c);if(!F||G(23)!="658953496"&&G(23)!="658953495"|| 
c.google_read_gcl_cookie_opt_out||c.google_conversion_domain||c.google_remarketing_only)var Gd="";else{var Pb=Uf(c),y={};c.google_gcl_cookie_domain&&(y.domain=c.google_gcl_cookie_domain);c.google_gcl_cookie_flags&&(y.flags=c.google_gcl_cookie_flags);c.google_gcl_cookie_max_age_seconds!=null&&(y.X=c.google_gcl_cookie_max_age_seconds);c.google_gcl_cookie_path&&(y.path=c.google_gcl_cookie_path);Pb&&(y.prefix=Pb);var Da=!1;Da=Da===void 0?!0:Da;var Za=ie(y.prefix);if(yd[Za])Ad(y),Bd(y);else if(he(Za,y.path, 
y.domain)){var Hd=zd[ie(y.prefix)]||{id:void 0,V:void 0};if(Da){var Id=Hd.id,Jd=Hd.V,Kd=ie(y.prefix),$a=yd[Kd];if($a){var Ld=$a.split(".");if(Ld.length===2){var Md=Number(Ld[1])||0;if(Md){var Nd=$a;Id&&(Nd=$a+"."+Id+"."+(Jd?Jd:Math.floor(fc()/1E3)));ce(Kd,Nd,y,Md*1E3)}}}}Ad(y);Bd(y)}else{b:{var Od=Oc(I.location.href),Pd=N(Od,"host",!1);if(Pd&&Pd.match(Jc)){var Qd=N(Od,"path");if(Qd){var Rd=Qd.split("auiddc=");if(Rd.length>1){var Sd=Rd[1].split(";")[0].split("?")[0];break b}}}Sd=void 0}var Td=Sd;Td? 
(H(17),yd[Za]=Td):Da&&(ce(ie(y.prefix),[String(Math.round(Math.random()*2147483647)),Math.round(fc()/1E3)].join("."),y),he(Za,y.path,y.domain),Ad(y,!0),Bd(y,!0))}var Ud=yd[ie(Pb)];Gd=Ud?Z("auid",Ud):""}var Ag=Gd,Vd=c.google_conversion_page_url,Bg=c.google_conversion_referrer_url,Ea="";if(b){if(a.top==a)var Wd=0;else{var Qb=a.location.ancestorOrigins;Wd=Qb?Qb[Qb.length-1]==a.location.origin?1:2:ta(a.top)?1:2}var Xd=Wd;var Yd=Vd?Vd:Xd==1?a.top.location.href:a.location.href;var Zd="";F&&E(["509562772", 
"509562773"],mb,21);if(F&&(G(21)=="509562773"||G(21)=="509562772")){for(var V,W=a,$d=W;W&&W!=W.parent;)W=W.parent,ta(W)&&($d=W);V=$d;var Fa=V.location.href;if(V===V.top)var ae={url:Fa,La:!0};else{var Rb=!1,Sb=V.document;Sb&&Sb.referrer&&(Fa=Sb.referrer,V.parent===V.top&&(Rb=!0));var Tb=V.location.ancestorOrigins;if(Tb){var Ub=Tb[Tb.length-1],be;Ub&&((be=Fa)==null?void 0:be.indexOf(Ub))===-1&&(Rb=!1,Fa=Ub)}ae={url:Fa,La:Rb}}var Vb=ae;Vb.url&&Yd!==Vb.url&&(Zd=Vb.url)}Ea+=Z("frm",Xd);Ea+=Z("url",Pf(Yd)); 
Ea+=Z("ref",Pf(Bg||b.referrer));Ea+=Z("top",Pf(Zd))}var Eg=[r,v,x,D,K,R,Ya,Fb,kg,lg,mg,ng,og,pg,Mb,qg,rg,sg,tg,ug,wg,xg,yg,zg,Ag,Ea,Wf(b),Zf(c.google_additional_params),Zf(c.google_remarketing_only?{}:c.google_additional_conversion_params),"&hn="+Of("www.googleadservices.com"),$f(a),ag(a)].join(""),de=xb(),Wb=Eg+(de.length>0?"&debug_experiment_id="+de:"");if(c.google_remarketing_only||c.google_conversion_domain)var ee=Wb;else{var Fg=[Z("mid",c.google_conversion_merchant_id),Z("fcntr",c.google_basket_feed_country), 
Z("flng",c.google_basket_feed_language),Z("dscnt",c.google_basket_discount),Z("bttype",c.google_basket_transaction_type)].join("");if(c){var Xb=c.google_conversion_items;if(Xb){for(var Yb=[],Zb=0,Gg=Xb.length;Zb<Gg;Zb++){var na=Xb[Zb],oa=[];na&&(oa.push(Sf(na.value)),oa.push(Sf(na.quantity)),oa.push(Sf(na.item_id)),oa.push(Sf(na.start_date)),oa.push(Sf(na.end_date)),Yb.push("("+oa.join("*")+")"))}var $b=Yb.length>0?"&item="+Yb.join(""):""}else $b=""}else $b="";var fe=[Wb,Fg,$b].join("");ee=fe.length> 
4E3?[Wb,Z("item","elngth")].join(""):fe}l=m+ee;d===1||d===6?l+=[Z("gcp",1),Z("sscte",1),Z("ct_cookie_present",1)].join(""):d==3&&(l+=Z("gcp",1),l+=Z("ct_cookie_present",1));if(rb){var ge=Df();ge!==void 0&&(l+=Z("us_privacy",ge||"error"))}Vf(c)&&(l=c.T?l+Z("gbcov",1):l+Z("gbcov",0));return l} 
function bg(a,b,c,d,e,f,g){return'<iframe name="'+a+'"'+(g?' id="'+g+'"':"")+' title="'+b+'" width="'+d+'" height="'+e+'"'+(c?' src="'+c+'"':"")+' frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true"'+(f?' style="display:none"':"")+' scrolling="no"></iframe>'} 
function cg(a){return{ar:1,bg:1,cs:1,da:1,de:1,el:1,en_AU:1,en_US:1,en_GB:1,es:1,et:1,fi:1,fr:1,hi:1,hr:1,hu:1,id:1,is:1,it:1,iw:1,ja:1,ko:1,lt:1,nl:1,no:1,pl:1,pt_BR:1,pt_PT:1,ro:1,ru:1,sk:1,sl:1,sr:1,sv:1,th:1,tl:1,tr:1,vi:1,zh_CN:1,zh_TW:1}[a]?a+".html":"en_US.html"} 
function dg(a,b,c){function d(h,k,l,m,r){m=m?' style="display:none"':"";return"<img "+(r&&Cb()?"attributionsrc ":"")+'height="'+l+'" width="'+k+'" border="0" alt="" src="'+h+'"'+m+" />"}Bb()&&Jb(2);var e="";c.google_remarketing_only&&c.google_enable_display_cookie_match&&!ac&&(F&&E(["376635470","376635471"],jb,2),e=c.google_remarketing_only&&c.google_enable_display_cookie_match&&!ac&&F&&G(2)=="376635471"?bg("google_cookie_match_frame","Google cookie match frame","https://bid.g.doubleclick.net/xbbe/pixel?d=KAE", 
1,1,!0,null):"");c.google_remarketing_only&&!c.google_conversion_domain&&F&&E(["759238990","759238991"],pb,13);!c.google_remarketing_only||c.google_conversion_domain||F&&(G(14)=="759248991"||G(14)=="759248990")||F&&E(["759248990","759248991"],ob,14);c.google_conversion_linker!==!1&&Bf(c.google_gcl_cookie_prefix);var f=Xf(a,b,c,c.google_remarketing_only?2:0);if(c.google_conversion_format==0&&c.google_conversion_domain==null)return'<a href="https://services.google.com/sitestats/'+(cg(c.google_conversion_language)+ 
"?cid="+Of(c.google_conversion_id))+'" target="_blank">'+d(f,135,27,!1,!1)+"</a>"+e;if(c.google_conversion_snippets!==void 0&&c.google_conversion_snippets>1||c.google_conversion_format==3){var g=f;c.google_conversion_domain==null&&(g=c.google_conversion_format==3?f:ue(f,"fmt",3));f=void 0;Cb()&&!c.google_remarketing_only&&(f={attributionsrc:""});return eg(a,b,c,g,f)?e:d(g,1,1,!0,!c.google_remarketing_only)+e}g=null;!c.google_conversion_domain&&eg(a,b,c,f)&&(g="goog_conv_iframe",f="");return bg("google_conversion_frame", 
"Google conversion frame",f,c.google_conversion_format==2?200:300,c.google_conversion_format==2?26:13,!1,g)+e}function eg(a,b,c,d,e){if(c.google_conversion_domain)return!1;try{return!!ve(a,b,d,null,void 0,e)}catch(f){return!1}} 
function fg(a){if(a.google_conversion_type==="landing"||!a.google_conversion_id||a.google_remarketing_only&&a.google_disable_viewthrough)return!1;a.google_conversion_date=new Date;a.google_conversion_time=a.google_conversion_date.getTime();a.google_conversion_snippets=typeof a.google_conversion_snippets==="number"&&a.google_conversion_snippets>0?a.google_conversion_snippets+1:1;a.google_conversion_first_time===void 0&&(a.google_conversion_first_time=a.google_conversion_time);a.google_conversion_js_version= 
"9";a.google_conversion_format!=0&&a.google_conversion_format!=1&&a.google_conversion_format!=2&&a.google_conversion_format!=3&&(a.google_conversion_format=3);a.google_enable_display_cookie_match!==!1&&(a.google_enable_display_cookie_match=!0);return!0}function gg(a){for(var b=0;b<Mf.length;b++)a[Mf[b]]=null}function hg(a){for(var b={},c=0;c<Mf.length;c++)b[Mf[c]]=a[Mf[c]];for(c=0;c<Nf.length;c++)b[Nf[c]]=a[Nf[c]];return b} 
function Yf(){var a="";Bb()&&(a=Lb().map(function(b){return b.join("-")}).join("_"));return Z("li",a)}function $f(a){if(!tb||!a.__gsaExp||!a.__gsaExp.id)return"";a=a.__gsaExp.id;if(!bc(a))return"";try{var b=Number(a());return isNaN(b)?"":Z("gsaexp",b)}catch(c){return""}} 
function ag(a){function b(d,e){e!=null&&c.push(d+"="+encodeURIComponent(e))}if(!Ab())return"";a=Hf(a);if(!a)return"";var c=[];b("&uaa",a.architecture);b("&uab",a.bitness);b("&uam",a.model);b("&uap",a.platform);b("&uapv",a.platformVersion);a.wow64!=null&&b("&uaw",a.wow64?"1":"0");a.fullVersionList&&b("&uafvl",a.fullVersionList.map(function(d){return encodeURIComponent(d.brand||"")+";"+encodeURIComponent(d.version||"")}).join("|"));return c.join("")} 
function Zf(a){if(!a)return"";var b="",c;for(c in a)a.hasOwnProperty(c)&&(b+=Z(c,a[c]));return b}function Vf(a){return(a=a.google_gtm_experiments)&&a.gbcov?!0:!1}function Uf(a){return a.google_gcl_cookie_prefix&&a.google_gcl_cookie_prefix!=="_gcl"&&Kf.test(a.google_gcl_cookie_prefix)?a.google_gcl_cookie_prefix:""} 
function ig(a,b){var c;if(c=!b.google_remarketing_only)if(b.google_transport_url||!F||G(19)!="375603261"&&G(19)!="375603260")c=!1;else{b:{if(!Lf){hb("AzMBwcG8UIaKM1GV43UaxMDFsS7hsiLx0FXw9ULTOHJRGxkUVw+UPCxlzz5CudOm+WnidygXLcAHmad6rC6C9QEAAACUeyJvcmlnaW4iOiJodHRwczovL2dvb2dsZWFkc2VydmljZXMuY29tOjQ0MyIsImZlYXR1cmUiOiJBdHRyaWJ1dGlvblJlcG9ydGluZ0Nyb3NzQXBwV2ViIiwiZXhwaXJ5IjoxNzE0NTIxNTk5LCJpc1N1YmRvbWFpbiI6dHJ1ZSwiaXNUaGlyZFBhcnR5Ijp0cnVlfQ\x3d\x3d",a);if(!Ef()&&!hb(q("www.googleadservices.com","endsWith").call("www.googleadservices.com","google.com")?"":"A2kc5o2ErHAbqJvF2MHSdYtnc2Bp3n6Jn2kNeko6SgHH6zXBHn0+4BbAW2No9ylVJMkzJAPwMqCVHqXm+IF1DgQAAACKeyJvcmlnaW4iOiJodHRwczovL2dvb2dsZWFkc2VydmljZXMuY29tOjQ0MyIsImZlYXR1cmUiOiJQcml2YWN5U2FuZGJveEFkc0FQSXMiLCJleHBpcnkiOjE2OTUxNjc5OTksImlzU3ViZG9tYWluIjp0cnVlLCJpc1RoaXJkUGFydHkiOnRydWV9",a)){a=!1;break b}Lf=!0}a=Ef()}c=a}c&&(a=b.google_additional_conversion_params||{},c=b.google_gtm_experiments,a.capi=c&&c.apcm?"2":"1",b.google_additional_conversion_params= 
a)};var jg=ja(["https://www.googletagmanager.com/debug/bootstrap"]),vg=!1,Cg=document.currentScript&&document.currentScript.src||""; 
function Dg(a,b,c){try{if(!vg&&(vg=!0,!c.google_gtm)){var d=void 0,e=void 0,f=se(a.location.href,"gtm_debug");Hg(f)&&(d=2);d||b.referrer.indexOf("https://tagassistant.google.com/")!==0||(d=3);!d&&Na(b.cookie.split("; "),"__TAG_ASSISTANT=x")>=0&&(d=4);d||(e=b.documentElement.getAttribute("data-tag-assistant-present"),Hg(e)&&(d=5));if(d){var g="AW-"+(c.google_conversion_id||"");if(!a["google.tagmanager.debugui2.queue"]){a["google.tagmanager.debugui2.queue"]=[];var h=fb(jg),k=new p.Map([["id",g],["src", 
"LEGACY"],["cond",d]]),l=Ha(h).toString(),m=l.split(/[?#]/),r=/[?]/.test(l)?"?"+m[1]:"";var v=gb(m[0],r,/[#]/.test(l)?"#"+(r?m[2]:m[1]):"",k);var x=ib("SCRIPT",b);Ma(x,v);var D=b.getElementsByTagName("script")[0];D&&D.parentNode&&D.parentNode.insertBefore(x,D)}a["google.tagmanager.debugui2.queue"].push({messageType:"LEGACY_CONTAINER_STARTING",data:{id:g,scriptSource:Cg}})}}}catch(K){}}function Hg(a){if(a==null||a.length===0)return!1;a=Number(a);var b=Date.now();return a<b+3E5&&a>b-9E5};function Ig(a){if(a.prerendering)return 3;var b;return(b={visible:1,hidden:2,prerender:3,preview:4,unloaded:5,"":0}[a.visibilityState||a.webkitVisibilityState||a.mozVisibilityState||""])!=null?b:0}function Jg(a){var b;a.visibilityState?b="visibilitychange":a.mozVisibilityState?b="mozvisibilitychange":a.webkitVisibilityState&&(b="webkitvisibilitychange");return b}function Kg(a,b){if(Ig(b)===3)return!1;a();return!0} 
function Lg(a,b){function c(){!f&&Kg(a,b)&&(f=!0,typeof b.removeEventListener==="function"&&b.removeEventListener(g,c,!1))}var d=d===void 0?!1:d;if(!Kg(a,b))if(d){var e=function(){typeof b.removeEventListener==="function"&&b.removeEventListener("prerenderingchange",e,!1);a()};typeof b.addEventListener==="function"&&b.addEventListener("prerenderingchange",e,!1)}else{var f=!1,g=Jg(b);g&&typeof b.addEventListener==="function"&&b.addEventListener(g,c,!1)}};function Mg(a){var b=q(Object,"assign").call(Object,{},a);a=a.id;b=(delete b.id,b);if(q(Object,"keys").call(Object,b).length)throw Error("Invalid attribute(s): "+q(Object,"keys").call(Object,b));return db({id:a})};F=new function(){var a=[];var b=0,c;for(c in zb)a[b++]=zb[c];a=a===void 0?[]:a;this.ca={};this.A={};for(b=0;b<a.length;++b)this.A[a[b]]=""};E(["466465925","466465926"],lb,20);Ab()&&Jf();F&&E(["592230570","592230571"],kb,16);Bb()&&(Jb(1),Kb()); 
function Ng(a,b,c,d){function e(m,r,v){v=v===void 0?function(){}:v;var x=new Image;x.onload=m;x.onerror=v;x.src=r}function f(){--g;if(g<=0){var m=ke(a,!1),r=m[b];r&&(delete m[b],m=r[0],typeof m==="function"&&m())}}d=d===void 0?[]:d;var g=c.length+1;if(c.length===2){var h=c[0],k=c[1];qe(h,0,"rmt_tld",h.search(re))>=0&&qe(h,0,"ipr",h.search(re))>=0&&!k.match(oe)[6]&&(k+=pe(h),c[1]=ue(k,"rmt_tld","1"))}for(h={I:0};h.I<c.length;h={I:h.I},h.I++){k=c[h.I];var l=se(k,"fmt");switch(Number(l)){case 1:case 2:(l= 
a.document.getElementById("goog_conv_iframe"))&&!l.src?rc(k,f,l):e(f,k);break;case 4:ve(a,a.document,k,f);break;case 5:if(a.navigator&&a.navigator.sendBeacon)if(a.navigator.sendBeacon(k,"")){f();break}else k=ue(k,"sendb",2);k=ue(k,"fmt",3);e(f,k);break;default:l=void 0,d&&d[h.I]&&(l=function(m){return function(){tc(d[m.I])&&f()}}(h)),e(f,k,l)}}f()} 
for(var Og=["GooglemKTybQhCsO"],Pg=z,Qg;Og.length&&(Qg=Og.shift());)Og.length||Ng===void 0?Pg[Qg]&&Pg[Qg]!==Object.prototype[Qg]?Pg=Pg[Qg]:Pg=Pg[Qg]={}:Pg[Qg]=Ng; 
(function(a,b,c){if(a){Dg(a,c,a);try{if(fg(a)){var d=hg(a);F&&E(["375603260","375603261"],ub?1:0,19);F&&E(["512247838","512247839"],vb?1:0,22);F&&E(["658953495","658953496"],nb,23);if(Ig(c)==3){var e="google_conversion_"+Math.floor(Math.random()*1E9);Oa(c,Mg({id:e}));Lg(function(){try{ig(c,d);var f=c.getElementById(e);if(f){var g=kc(dg(a,c,d));if(f.nodeType===1&&/^(script|style)$/i.test(f.tagName))throw Error("");f.innerHTML=La(g)}}catch(h){}},c)}else ig(c,d),Oa(c,kc(dg(a,c,d)))}}catch(f){}gg(a)}})(window, 
navigator,document);}).call(this);
